### ISSUE TITLE
WinError 10060

### ISSUE THREAD

**Issue by sa9St** [bharat0/Palringo-Typing-Cheater#1]
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by bharat0** [comment]
That's a common problem you may face during the execution. Palringo keeps changing its connection setting time to time so you need to update Socket IP and Port whenever you see this kind of error. Use [wireshark ](https://www.wireshark.org/) to analyze packets and find new server IP and port.
